### ISSUE TITLE
`php artisan native:serve` hangs (Windows 11)

### ISSUE THREAD

**Issue by Stridesdata** [NativePHP/laravel#301] opened 2024-05-12 18:55 UTC
### What were you trying to do?

I have an existing web app 
Laravel 10
Livewire 2.5
php 8.1
windows 11

I installed, and when I run the server command I get stuck indefinitely in

 Starting NativePHP app

 Running the dev script with npm...

 Fetching latest dependencies…
 

### What happened?

The native server was meant to run

### How to reproduce the bug

It might be only specific to me

### Package Versions

0.6.3

### PHP Version

8.1.8

### Laravel Version

10.48.0

### Node Version

20.11.1

### Which operating systems have you seen this occur on?

Windows

### OS version

win 11 (22H2)

### Notes

Can we get it to work?

**Comment by NawrasBukhari** [comment] 2024-05-12 22:40
This bug is puzzling. It was fine yesterday in the same setup you have. But as soon as I ran "php artisan native:build", it stopped working. Strangely, the build works perfectly, but in development, it doesn't open at all!

**Comment by avazquez-bit** [comment] 2024-05-13 15:17
It seems to be related with #300, the message is the same, but mine appears in dev console

**Comment by simonhamp** [comment] 2024-05-14 07:12
@Stridesdata are you running the command from Command Prompt or PowerShell?

Are you running directly on Windows and not via some virtualised environment like a Docker container or WSL2?

Please try running commands with the `-vvv` flag to increase the output verbosity level.

**Comment by simonhamp** [comment] 2024-05-14 07:13
@NawrasBukhari I believe your issue is related to #300 as @avazquez-bit says. Please can you pick up your conversation there?

**Comment by faridmcdato12345** [comment] 2024-05-15 09:50
I solve this by checking the laravel.log and fixing those error that occurs their.

**Comment by dnk2311** [comment] 2024-07-26 10:34
![image](https://github.com/user-attachments/assets/7b7cd7d9-881d-49d0-b8de-d4fbff35956f)

**Comment by simonhamp** [comment] 2024-11-13 08:18
Closing as a duplicate of #300

**Closed by simonhamp** 2024-11-13 08:18 UTC
Labels: bug, windows
