### ISSUE TITLE
[Bug]: native:serve won't start app window

### ISSUE THREAD

**Issue by arbazargani** [NativePHP/laravel#28] opened 2023-07-21 09:04 UTC
### What happened?

`php artisan native:serve` won't do anything at all.
just ends with no window or anything.
![image](https://github.com/NativePHP/laravel/assets/46598928/c31ccf1d-85d0-49f1-bca0-d01632578828)

### How to reproduce the bug

`php artisan native:serve`

### Package Version

0.1.0

### PHP Version

8.1.11

### Laravel Version

10.15.0

### Which operating systems does with happen with?

Windows

**Comment by erikroznbeker** [comment] 2023-07-21 10:00
On mac, same error:

```
dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
error during start dev server and electron app:
Error: No electron app entry file found: /..../vendor/nativephp/electron/resources/js/out/main/index.js
    at ensureElectronEntryFile (/.../vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-3592fc5a.js:26:23)
    at Object.startElectron (/.../vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-3592fc5a.js:120:5)
    at createServer (/.../vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-86ea98bb.js:74:21)
    at async CAC.<anonymous> (/.../vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/cli.js:48:9)
error Command failed with exit code 1.
```

**Comment by Rueff19** [comment] 2023-07-21 10:02
> On mac, same error:
> 
> ```
> dev server running for the electron renderer process at:
> 
>   ➜  Local:   http://localhost:5173/
>   ➜  Network: use --host to expose
> error during start dev server and electron app:
> Error: No electron app entry file found: /..../vendor/nativephp/electron/resources/js/out/main/index.js
>     at ensureElectronEntryFile (/.../vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-3592fc5a.js:26:23)
>     at Object.startElectron (/.../vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-3592fc5a.js:120:5)
>     at createServer (/.../vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-86ea98bb.js:74:21)
>     at async CAC.<anonymous> (/.../vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/cli.js:48:9)
> error Command failed with exit code 1.
> ```

duplicate of https://github.com/NativePHP/laravel/issues/27

**Comment by Nielson** [comment] 2023-07-22 06:00
Same problem here. @rappasoft posted a temporary fix in #27 (https://github.com/NativePHP/electron/issues/10#issuecomment-1644651637) which worked for me.

**Comment by w0rd-driven** [comment] 2023-07-22 22:06
The cert files have been included for me but there were some extra steps I needed, in case this helps. I also saw no errors that pointed to any problems.

- Restart my machine - no clue why this was necessary but it would show in the Dock but the MenuBar wasn't visible, nor was the default Window.
- Manually change the package.json in vendor/nativephp/electron/resources/js/package.json to @nativephp/electron-plugin. This was committed recently (https://github.com/NativePHP/electron/blob/main/resources/js/package.json#L30) but was not pulled locally.
- There is a PR to change the `app` entry point in main/index.js to the different npm package (https://github.com/NativePHP/electron/blob/main/resources/js/src/main/index.js#L2) that was merged.

I suspect the JS changes will be published to npm soon where a reboot may or may not be necessary.

**Comment by ShaneShipston** [comment] 2023-07-23 16:35
If you are willing to make some code modifications you can follow these instructions to get native:serve to work on Windows. This will only get native:serve to work. It's as far as I've tried so far.

[NativePHP Windows Support](https://gist.github.com/ShaneShipston/8bb7cabc423cf0cc64da0eacafa53171)

**Comment by arbazargani** [comment] 2023-07-24 16:53
@franvilladaa i'm on win11 too & no bro, no fix yet. even updating nativephp version to latest minor update via composer, but problem exists. sorrey. hope problems solve soon & we can test nativephp too.

**Comment by cdmathukiya** [comment] 2023-07-28 06:58
still getting this issue
![image](https://github.com/NativePHP/laravel/assets/18529326/c5953d3a-3b77-4cb7-aaa4-9847224c8ae7)

https://www.awesomescreenshot.com/video/19493343?key=b39559aec70f07a12de5ba40c1c4ddbe

**Comment by EJyoungc** [comment] 2023-07-30 12:27
i am the same issue but  app selector appears
![Screenshot (17)](https://github.com/NativePHP/laravel/assets/34107946/565830f7-5289-4f49-afe8-0f6b731f8449)

**Comment by simonhamp** [comment] 2024-04-30 21:21
A whole load of improvements to development and building on Windows have been made recently.

Please update to nativephp/electron v0.6 and try again.

**Closed** 2024-04-30 21:21 UTC
Labels: bug, windows

**Comment by aknessy** [comment] 2025-02-01 14:17
What solved this issue for me on Windows 11 was running:
`npm install` & `npm run build`
