### ISSUE TITLE
[Bug]: php artisan native:serve error -86

### ISSUE THREAD

**Issue by benjam-es** [NativePHP/laravel#145] opened 2023-08-03 18:17 UTC
### What happened?

When I try to run php artisan native:serve, I get console errors and am unable to get menus items to change or a menu icon to add to the tray.

### How to reproduce the bug

Run php artisan native:serve

### Package Version

^0.3.3

### PHP Version

8.2.8

### Laravel Version

10.17.1

### Node Version

v16.0.0

### Which operating systems does with happen with?

macOS

### Notes

Also tried with node 18 and 20

macOS: ventura, m2 chip

Full message in console:

------------------

start electron app...

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at execFile (node:child_process:359:17)
    at node:child_process:252:21
    at node:electron/js2c/asar_bundle:2:3130
    at /Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:47:69
    at Generator.next (<anonymous>)
    at /Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:4:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

API server started on port 4000

Starting PHP server... /Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/resources/php/php artisan serve /Users/admin/Code/websites/demo

Making sure app folders are available

(node:95800) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at callPhp (/Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:53:38)
    at /Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:141:9
    at Generator.next (<anonymous>)
    at /Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:4:12)
    at /Users/admin/Code/websites/demo/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:122:45
    at new Promise (<anonymous>)
(Use `Electron --trace-warnings ...` to show where the warning was created)

(node:95800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

-----
N.B I get this same error when trying to run https://github.com/simonhamp/cronikl

**Comment by benjam-es** [comment] 2023-08-03 18:19
Also using Herd for serving sites

**Comment by simonhamp** [comment] 2023-08-03 18:29
I was bumping into this today too @benjam-es - I got past it by deleting the `vendor` folder and basically starting from scratch. See https://github.com/NativePHP/laravel/issues/120#issuecomment-1663948613

Going to close this as a dupe of that issue

**Closed by simonhamp** 2023-08-03 18:29 UTC
Labels: bug
