### ISSUE TITLE
[Bug]: Label and DockIcon don't show in Ubuntu

### ISSUE THREAD

**Issue by lon9man** [NativePHP/laravel#211] opened 2023-09-26 13:13 UTC
### What happened?

Provided code dosn't show in Ubuntu 20.04:
1. text label 
2. dock icon

```
MenuBar::create()
               ->showDockIcon()
               ->label( 'Status: Online' )
               ->withContextMenu(
                   Menu::new()
                       ->label( 'My Application' )
                       ->separator()
                       ->link( 'https://nativephp.com', 'Learn more…' )
                       ->separator()
                       ->quit()
               )
               ->onlyShowContextMenu();
```

### How to reproduce the bug

1. create test project using [instructions](https://nativephp.com/docs/1/getting-started/installation)
2. add above code to create `MenuBar`

### Package Version

0.4.0

### PHP Version

8.1.23

### Laravel Version

10.21.0

### Node Version

18.17.1

### Which operating systems does with happen with?

Linux

**Comment by simonhamp** [comment] 2024-04-28 21:26
Are you using the MenuBar class directly, or the Facade (`\Native\Laravel\Facades\MenuBar`)?

You may need also call `->create()` at the end.

**Comment by simonhamp** [comment] 2024-04-28 21:38
I've done a bit of digging and realised that we're using a third-party package called [`menubar`](https://github.com/max-mapper/menubar) which seems to be pretty old.

It seems that [it doesn't have great support for Linux](https://github.com/max-mapper/menubar/blob/master/WORKING_PLATFORMS.md) and ymmv depending on which distro you're using.

**Comment by lon9man** [comment] 2024-04-28 21:55
So, it will not be fixed or implemented in different way? Ubuntu 24.04 was released couple days ago)

**Comment by simonhamp** [comment] 2024-04-28 22:16
At the moment, no. I'm currently supporting NativePHP on my own and I don't have an Ubuntu setup on which to test this issue let alone begin implementing an alternative.

**Comment by simonhamp** [comment] 2024-05-01 06:08
Duplicate of #102

**Closed** 2024-05-01 06:09 UTC
Labels: bug, linux
