### ISSUE TITLE
[Bug]: TTY mode is not supported on Windows platform.

### ISSUE THREAD

**Issue by Peeyush415** [NativePHP/laravel#44] opened 2023-07-22 10:07 UTC
### What happened?

I try to install and setup in my system, but its show some error in console
![Screenshot 2023-07-22 153145](https://github.com/NativePHP/laravel/assets/56077288/a66f551f-745d-4701-ab
![Screenshot 2023-07-22 153208](https://github.com/NativePHP/laravel/assets/56077288/fb2a6896-a211-4930-ac6b-ad3ba76c114c)
f4-2196ef12ef59)

### How to reproduce the bug

setup a laravel first and try to setup the nativephp

### Package Version

0.1.0

### PHP Version

8.0.0

### Laravel Version

10.0.0

### Which operating systems does with happen with?

Windows

### Notes

Please update with some demo

**Comment by simonhamp** [comment] 2023-07-22 10:18
Duplicate of #8

**Closed by simonhamp** 2023-07-22 10:18 UTC
Labels: bug
