### ISSUE TITLE
[Bug]: Cannot send a notification from scheduler or using Tinker

### ISSUE THREAD

**Issue by jornicornelese** [NativePHP/laravel#285] opened 2024-05-01 17:59 UTC
### What were you trying to do?

I created a job in which I have a notification.
I'm trying to trigger it within the scheduler using:
`$schedule->job(MyNotification::class)->everyMinute();`

Or trigger it within tinker using DispatchSync.

To test that my Job works I used a DD as well, which does trigger, but the notification won't.

The notification does trigger when used within the NativeAppServiceProvider.

### What happened?

I expected the Notification to trigger, but nothing pops up.

### How to reproduce the bug

Here is my Job:

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Native\Laravel\Facades\Notification;

class MyNotification
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        Notification::title('Hello from NativePHP')
            ->message('This is a detail message coming from your Laravel app.')
            ->show();

        dd('Notification sent!');
    }
}
```

### Package Versions

"nativephp/electron": "0.6.1", "nativephp/laravel":"0.5.0", "nativephp/php-bin": "0.4.0"

### PHP Version

v8.2.18

### Laravel Version

v10.48.10

### Node Version

v18.15

### Which operating systems have you seen this occur on?

macOS

### OS version

14.2.1 (23C71)

**Comment by simonhamp** [comment] 2024-05-02 19:22
When I run this code (also on macOS 14, Laravel 10), the notification shows fine. So I think the problem isn't in NativePHP, but on your system

There are a few things to check:

#### 1. Are Electron Notifications enabled in your System Preferences?

![Screenshot 2024-05-02 at 20 17 20](https://github.com/NativePHP/laravel/assets/31628/49955a12-b8f1-4e3f-9573-c6870110fd02)

If they're 'Off' (as demonstrated above), please turn them on (as demonstrated below) and try again.

![Screenshot 2024-05-02 at 20 19 15](https://github.com/NativePHP/laravel/assets/31628/dfea0347-9558-4555-8d36-9c456397d1d0)

#### 2. Do you have Do Not Disturb on?

![Screenshot 2024-05-02 at 20 18 02](https://github.com/NativePHP/laravel/assets/31628/29391051-07d0-42f2-a3e9-660f04d1c103)

If so, please turn it off and try again.

Do Not Disturb will suppress most notifications (except those explicitly allowed during DND):

![Screenshot 2024-05-02 at 20 21 49](https://github.com/NativePHP/laravel/assets/31628/8786815a-88ac-4551-8240-365333601a26)
---
If you're still having issues, please let me know.

**Comment by simonhamp** [comment] 2024-05-06 11:13
@jornicornelese I'm going to close this issue for now. If you still haven't been able to figure out the cause of your troubles after trying the above, feel free to re-open with more details.

**Closed by simonhamp** 2024-05-06 11:13 UTC
Labels: bug
