### ISSUE TITLE
[Bug]: Built app won't open on Windows 10 / 11

### ISSUE THREAD

**Issue by kuai667** [NativePHP/laravel#192] opened 2023-08-24 08:08 UTC
### What happened?

So, I've done a simple app in Native for both Windows and Mac. I've built it for both versions and although it works ok on Mac, on Windows 10 and 11 (Tested with three different computers), after running the setup and launching the app, nothing gets opened, it just runs as a background process.
Any idea of what could it be? I even tried with a clean copy of Laravel/Native and have the same problem.

### How to reproduce the bug

Create a clean copy of Laravel with native and build it for Windows. Run the setup on the Windows machine.

### Package Version

0.4.0

### PHP Version

8.2.0

### Laravel Version

10.19.0

### Node Version

9.5.0

### Which operating systems does with happen with?

Windows

### Notes

I developed it in a Macbook Pro 2019 - intel (Ventura 13.5.1)

**Comment by A3Brothers** [comment] 2023-08-25 14:13
Same happening with me, build is working fine in my MacBook Air (2017) but when I make a build for windows and run it in windows nothing gets opened, it just runs as a background process.

**Comment by Sagmedjo** [comment] 2023-08-26 10:45
Same for me built it but now window is pooping up. But I've built it with windows

**Comment by kuai667** [comment] 2023-08-26 14:22
Hi! I wouldn't refer to that error because in my case, the .exe and setup files do appear

**Comment by ivang76** [comment] 2023-08-28 12:35
Same also on my side, compiling/building on Macbook pro M1 and testing the build on Win10 and Win11 (and also on an arm version of Win11 under Parallels Desktop).

**Comment by MikePonce-UwU** [comment] 2023-09-20 18:53
In my case, for some reason, it won't stop running the `php artisan native:install` command, it stands still in:

> Publishing NativePHP Service Provider

I don't know why this happens like so.

**Comment by paulocardozo** [comment] 2023-10-09 19:23
> In my case, for some reason, it won't stop running the `php artisan native:install` command, it stands still in:
> 
> > Publishing NativePHP Service Provider
> 
> I don't know why this happens like so.

Are you using Windows to?  Because I'm using Windows 11, tried to do that and same occurs..  I did some search in docs and found a important point, seems this package works only in MacOS or Linux..

**Comment by wellyrm** [comment] 2023-10-17 00:17
Got same error, but following this https://github.com/NativePHP/laravel/issues/105 the app can run in my Windows 11.

**Comment by MdAnowarHosen** [comment] 2023-12-08 09:27
Got same error!

**Comment by gitnyasha** [comment] 2023-12-12 13:03
Is there a solution for this yet?

**Comment by EPuigdemont** [comment] 2024-01-02 21:51
Has anyone managed to get this working yet? It runs just fine on Mac but won't open the window when trying to run the app in Windows 10.
I even attempted compiling it in the same W10 machine I'm trying to run it, where I have confirmed that native:serve does work.

**Comment by AlexJanson** [comment] 2024-01-03 00:09
> Has anyone managed to get this working yet? It runs just fine on Mac but won't open the window when trying to run the app in Windows 10. I even attempted compiling it in the same W10 machine I'm trying to run it, where I have confirmed that native:serve does work.

I've managed to get it to work on Windows 11 using the changes in this pull request https://github.com/NativePHP/electron/pull/79. I'm building and serving using WSL 2 & Laravel Sail.

**Comment by EPuigdemont** [comment] 2024-01-03 13:15
The issue was that on mac it's not mandatory to create a Window::open(); instance in the NativeAppServiceProvider to have the window appear, when I added it to the service provider it opens the application just fine.

**Comment by patrickcarlohickman** [comment] 2024-01-11 01:41
I ran into this issue and was also able to resolve it using the the PR https://github.com/NativePHP/electron/pull/79. I'm using WSL2 on Windows 10.

`php artisan native:serve` worked fine from inside WSL2, but when I built the application for Windows (`php artisan native:build win`) and transferred the executable to the host machine, it would start 3 "Laravel" background processes, but no window would pop up.

After updating my project to point to the PR, and reinstalling/rebuilding, everything worked fine on my Windows machine.

**Comment by simonhamp** [comment] 2024-04-28 22:12
The fixes in #79 were released earlier in [v0.5.1](https://github.com/NativePHP/electron/releases/tag/0.5.1).

Please could you all run `composer update` to get the latest version and try again?

Please also note that in the next few days a further update will be coming with an improved Windows build that I would love you all to test out.

**Comment by simonhamp** [comment] 2024-04-30 20:20
Building and publishing for Windows hasn't been officially supported... until now.

Please update to nativephp/electron v0.6 and try again.

**Closed by simonhamp** 2024-04-30 20:20 UTC
Labels: bug, windows
